### ISSUE TITLE
Getting error when importing digest-crc as a Fastlane dependency

### ISSUE THREAD

**Issue by xalbillos** [postmodern/digest-crc#19] opened 2020-07-02 10:04 UTC
```
Fetching digest-crc 0.6.0 (was 0.4.1)
Installing digest-crc 0.6.0 (was 0.4.1) with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
```

This error only happens on 0.6.0, which was released today. Didn't happen with older versions.

**Comment by limfinity** [comment] 2020-07-02 10:15
Same thing for me. I had to `sudo gem install digest-crc -v '0.6.0' --source 'https://rubygems.org/'` to resolve the issue. 😬

**Comment by xalbillos** [comment] 2020-07-02 10:24
Hmmm I'm using bundler on a remote build machine, can't do that directly, is there a workaround or an incoming fix ?

**Comment by stefanomondino** [comment] 2020-07-02 10:36
add `gem "rake"` to your Gemfile for now.

Hopefully this will get fixed in future releases, but fortunately the workaround is really easy :)

**Comment by xalbillos** [comment] 2020-07-02 11:25
> add `gem "rake"` to your Gemfile for now.
> 
> Hopefully this will get fixed in future releases, but fortunately the workaround is really easy :)

What does that do ?

**Comment by stefanomondino** [comment] 2020-07-02 14:10
@xalbillos `rake` is a dependency required by digest-crc. They simply forgot (I guess) to declare it as an explicit dependency and using it in the code taking for granted that it will be installed on every machine.

Adding the explicit dependency to the Gemfile ensures that your build machine properly installs it before running fastlane.
Rake is one of the most common gems in Ruby.

**Comment by xalbillos** [comment] 2020-07-02 14:45
> @xalbillos `rake` is a dependency required by digest-crc. They simply forgot (I guess) to declare it as an explicit dependency and using it in the code taking for granted that it will be installed on every machine.
> 
> Adding the explicit dependency to the Gemfile ensures that your build machine properly installs it before running fastlane.
> Rake is one of the most common gems in Ruby.

Oh man, thanks for the detailed explanation. Now I see further down in the log where you found the reference to rake:
``find_spec_for_exe': can't find gem rake (>= 0.a) with executable rake

(Gem::GemNotFoundException)

from /Users/admin/.rbenv/versions/2.7.0/lib/ruby/2.7.0/rubygems.rb:294:in

`activate_bin_path'

	from /Users/admin/.rbenv/versions/2.7.0/bin/rake:23:in `<main>'`

Thanks. I hope they provide a new release, but will try this.

**Comment by rogerluan** [comment] 2020-07-02 15:54
This issue is a duplicate of https://github.com/postmodern/digest-crc/issues/18
[This fix](https://github.com/postmodern/digest-crc/issues/18#issuecomment-652889761) is better so you don't have to install rake system wide 👍

**Comment by postmodern** [comment] 2020-07-02 22:45
Ugh, I forgot that bundler excludes "built-in" gems such as rake or irb, forcing them to be declared as runtime deps.

**Closed** 2020-07-02 22:46 UTC

**Comment by postmodern** [comment] 2020-07-02 23:12
`rake` is now a full dependency as of 9efa59da2917c8d916a60a6680d420c172cfa4ed.

**Comment by postmodern** [comment] 2020-07-03 00:37
0.6.1 has also been pushed with the fix.

**Comment by rjuevesano** [comment] 2021-03-05 13:37
can someone help me why I'm getting this?

```
source "https://rubygems.org"

gem "fastlane"
gem "rake"

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
```

![image](https://user-images.githubusercontent.com/4033035/110122702-e9a2f900-7dfa-11eb-98cb-5b61af617f69.png)

**Comment by postmodern** [comment] 2021-03-06 00:11
@rjuevesano can I get the log file, version of bundler, and version of ruby 2.5 you're using? Looks like bundler or rubygems isn't finding `rake`. Also, maybe try updating bundler or rubygems?

**Comment by rjuevesano** [comment] 2021-03-08 07:50
hi @postmodern here's the log.

ruby
`ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin20]`

bundler
`Bundler version 2.2.13`

[logfile.txt](https://github.com/postmodern/digest-crc/files/6099692/logfile.txt)

**Comment by rjuevesano** [comment] 2021-03-09 07:38
@postmodern I got it working by adding this `gem "digest-crc", "~> 0.6.3"` to `Gemfile` and `gem 'rake'` to `Pluginfile`

**Comment by nysander** [comment] 2021-08-05 13:29
same here: https://stackoverflow.com/questions/68667183/bundle-update-error-on-macos-bigsur-apple-silicon-m1

**Comment by maxTeste** [comment] 2021-09-02 16:25
hey guys
can someone help me?
I'm trying to run fastlane with pipeline azure and then with fastlane call discord_notifier (https://github.com/nikolas-theodosis/fastlane-discord_notifier)
so
pipeline azure -> fastlane -> discord_notifier

if I only test fastlane with the discord notifier it works fine, but if the pipline triggers the fastlane (bundle exec fastlane dev) it doesn't work

erro on pipeline ->  bundle exec fastlane dev: 
![image](https://user-images.githubusercontent.com/75133022/131880383-0ce08bd4-c73a-433c-bc60-00cda8366a68.png)

![image](https://user-images.githubusercontent.com/75133022/131880717-96d4b1bb-cc25-4f6b-bf99-061e4ae308f7.png)

yaml file pipeline:
![image](https://user-images.githubusercontent.com/75133022/131880458-77d92eb5-17b5-4d14-a340-1b4ef2109aa0.png)

running only fastlane and notifier:
![image](https://user-images.githubusercontent.com/75133022/131880275-ef8df074-7c99-4e23-873c-dafcf2e67735.png)


![image](https://user-images.githubusercontent.com/75133022/131880310-d250bff5-1ae7-4fdd-9327-ea7f2a0de98d.png)

![image](https://user-images.githubusercontent.com/75133022/131880341-d82f6ed0-1984-4924-bfec-831f6e984e32.png)

**Comment by postmodern** [comment] 2021-09-03 00:44
@maxTeste that doesn't look like it's related to the above issue. Could you post the output of `bundle install` where it installs/compiles `digest-crc`?

**Comment by maxTeste** [comment] 2021-09-03 07:28
#32

**Comment by lusanyuss** [comment] 2022-07-19 02:34
always    installing digest-crc 0.6.4 with native extensions

**Comment by lusanyuss** [comment] 2022-07-19 02:36
![image](https://user-images.githubusercontent.com/4524247/179651987-c8aa6e4d-8737-4261-88c0-451fc9213748.png)

**Comment by lusanyuss** [comment] 2022-07-19 02:40
it installs all day what's wrong

**Comment by postmodern** [comment] 2022-07-19 03:40
@lusanyuss is it just taking a long time to install or is it only re-installing digest-crc 0.6.4 each time? Compiling the C extensions for digest-crc can take a minute, but you can watch the process using `top` or `htop`.
